### ISSUE TITLE
step height bug in latest 1.12.2 version

### ISSUE THREAD

**Issue by Aldaria-Games** [DenisMasterHerobrine/TravellersBoots#6] opened 2020-01-18 06:07 UTC
After taking off a pair of Mk2 boots, the step height increase effect remains active. I do not know for sure how long it lasts, but it seems like it lasts until next death.

This may affect 3 and 4 as well, it's worth a check at least.

**Comment by DenisMasterHerobrine** [comment] 2020-01-19 05:53
Hello, thanks for the report, my apologies for that bug in 1.12.2 since I fixed these things in only 1.14+ versions and forgot about 1.12.2 one. This bug is reproduced and will be fixed soon.

**Closed as completed** 2024-01-08 22:08 UTC
Labels: bug, 1.12
